Repository codestates-seb/seb42_main_006, pull requests merged in 2023-03, with the labels that each got.

#19 Feat/fe/sign up
  client/src/App.tsx
  client/src/conponent/Header.tsx
  client/src/conponent/Nav.tsx
  client/src/conponent/parts/Button.tsx
  client/src/conponent/parts/Input.tsx
  client/src/function/validFn.tsx
  client/src/icons/Icon.tsx
  client/src/page/Collect.tsx
  client/src/page/Login.tsx
  client/src/page/NotFound.tsx
  client/src/page/Posts.tsx
  client/src/page/Signup.tsx
  client/tailwind.config.js
  client/tsconfig.json
Labels: enhancement

#38 feat: main, mypage 레이아웃 & 기능 추가
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.tsx
  client/src/conponent/MapSearch.tsx
  client/src/conponent/Nav.tsx
  client/src/conponent/main/Category.tsx
  client/src/conponent/mypage/Paging.tsx
  client/src/conponent/mypage/UserEdit.tsx
  client/src/conponent/parts/Button.tsx
  client/src/conponent/parts/IconButton.tsx
  client/src/conponent/parts/InputNoH.tsx
  client/src/conponent/parts/KakaoMap.tsx
  client/src/conponent/parts/Selection.tsx
  client/src/conponent/parts/Tag.tsx
  client/src/conponent/parts/UserProfile.tsx
  client/src/function/request.ts
  client/src/function/validFn.tsx
  client/src/icons/MainIcon.tsx
  client/src/icons/MyIcon.tsx
  client/src/page/AddPost.tsx
  client/src/page/Collect.tsx
  client/src/page/CollectDeatail.tsx
  client/src/page/Login.tsx
  client/src/page/Main.tsx
  client/src/page/Mypage.tsx
  client/src/page/Posts.tsx
  client/src/page/Signup.tsx
  client/src/react-app-env.d.ts
  client/src/util/MyApi.tsx
  client/src/util/MyInput.tsx
Labels: documentation

#51 feat: mypage api 연결 확인 및 반응형 추가
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/conponent/Comment.tsx
  client/src/conponent/main/Category.tsx
  client/src/conponent/mypage/Paging.tsx
  client/src/conponent/mypage/UserEdit.tsx
  client/src/conponent/mypage/UserModal.tsx
  client/src/conponent/parts/AudioPlayer.tsx
  client/src/conponent/parts/IconButton.tsx
  client/src/conponent/parts/Input.tsx
  client/src/conponent/parts/InputNoH.tsx
  client/src/conponent/parts/KakaoMap.tsx
  client/src/conponent/parts/Player.tsx
  client/src/conponent/parts/Selection.tsx
  client/src/conponent/parts/Tag.tsx
  client/src/conponent/parts/YoutubeList.tsx
  client/src/conponent/parts/YoutubeListItem.tsx
  client/src/conponent/parts/YoutubePlayer.tsx
  client/src/function/request.ts
  client/src/function/validFn.ts
  client/src/function/youtubeApi.ts
  client/src/icons/Icon.tsx
  client/src/icons/MainIcon.tsx
  client/src/icons/MyIcon.tsx
  client/src/index.tsx
  client/src/page/AddPost.tsx
  client/src/page/Example.tsx
  client/src/page/Login.tsx
  client/src/page/Main.tsx
  client/src/page/Mypage.tsx
  client/src/page/PostDetail.tsx
  client/src/page/Signup.tsx
  client/src/react-app-env.d.ts
  client/src/style/GlobalStyles.ts
  client/src/style/Media.ts
  client/src/util/MyApi.tsx
  client/src/util/MyInput.tsx
Labels: documentation

#54 Feat/fe/youtube player
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/conponent/Comment.tsx
  client/src/conponent/CommentCreator.tsx
  client/src/conponent/Header.tsx
  client/src/conponent/MapSearch.tsx
  client/src/conponent/addPost/MapSearch.tsx
  client/src/conponent/addPost/MoviePreview.tsx
  client/src/conponent/addPost/PlaylistMaker.tsx
  client/src/conponent/mypage/UserEdit.tsx
  client/src/conponent/parts/Comment.tsx
  client/src/conponent/parts/CommentList.tsx
  client/src/conponent/parts/InputNoH.tsx
  client/src/conponent/parts/Selection.tsx
  client/src/conponent/postDetail/movie/YoutubePlayer.tsx
  client/src/conponent/postDetail/music/AudioPlayer.tsx
  client/src/conponent/postDetail/music/Player.tsx
  client/src/conponent/postDetail/music/YoutubeList.tsx
  client/src/conponent/postDetail/music/YoutubeListItem.tsx
  client/src/conponent/postDetail/restaurant/KakaoMap.tsx
  client/src/conponent/postDetail/restaurant/Slide.tsx
  client/src/icons/logo.svg
  client/src/page/AddPost.tsx
  client/src/page/CollectDeatail.tsx
  client/src/page/CollectPost.tsx
  client/src/page/Example.tsx
  client/src/page/Login.tsx
  client/src/page/PostDetail.tsx
  client/src/page/Signup.tsx
  client/src/style/GlobalStyles.ts
  node_modules/.package-lock.json
Labels: enhancement

#60 fix : 데이터와 화면 연동 오류 개선
  client/src/App.tsx
  client/src/conponent/CommentCreator.tsx
  client/src/conponent/Header.tsx
  client/src/conponent/Modal.tsx
  client/src/conponent/Nav.tsx
  client/src/conponent/addPost/PlaylistMaker.tsx
  client/src/conponent/collect/CollectItem.tsx
  client/src/conponent/main/BoxLi.tsx
  client/src/conponent/main/Category.tsx
  client/src/conponent/main/CommonLi.tsx
  client/src/conponent/mypage/UserEdit.tsx
  client/src/conponent/mypage/UserModal.tsx
  client/src/conponent/parts/Button.tsx
  client/src/conponent/parts/Comment.tsx
  client/src/conponent/parts/IconButton.tsx
  client/src/conponent/parts/InputNoH.tsx
  client/src/conponent/parts/Loading.tsx
  client/src/conponent/parts/PageButton.tsx
  client/src/conponent/parts/Selection.tsx
  client/src/conponent/post/PostItem.tsx
  client/src/conponent/post/PostList.tsx
  client/src/conponent/postDetail/movie/YoutubePlayer.tsx
  client/src/conponent/postDetail/music/AudioPlayer.tsx
  client/src/conponent/postDetail/music/Player.tsx
  client/src/conponent/postDetail/music/YoutubeList.tsx
  client/src/conponent/postDetail/music/YoutubeListItem.tsx
  client/src/function/request.ts
  client/src/icons/Icon.tsx
  client/src/page/AddPost.tsx
  client/src/page/Collect.tsx
  client/src/page/CollectDeatail.tsx
  client/src/page/CollectPost.tsx
  client/src/page/Login.tsx
  client/src/page/Main.tsx
  client/src/page/Mypage.tsx
  client/src/page/Posts.tsx
  client/src/page/Signup.tsx
  client/src/react-app-env.d.ts
  client/src/style/GlobalStyles.ts
  client/src/util/CollectPostApi.ts
  client/src/util/MyApi.ts
  client/src/util/MyInput.ts
  client/src/util/MyToken.ts
  client/src/util/PostApi.ts
  client/src/util/useIntersectorObsevet.tsx
Labels: bug

#72 Feat/fe/postapi
  client/src/App.tsx
  client/src/conponent/CommentCreator.tsx
  client/src/conponent/Header.tsx
  client/src/conponent/Modal.tsx
  client/src/conponent/collect/CollectItem.tsx
  client/src/conponent/mypage/UserEdit.tsx
  client/src/conponent/mypage/UserModal.tsx
  client/src/conponent/parts/Comment.tsx
  client/src/conponent/parts/CommentList.tsx
  client/src/conponent/parts/IconButton.tsx
  client/src/conponent/parts/InputNoH.tsx
  client/src/conponent/parts/UserProfile.tsx
  client/src/conponent/post/PostItem.tsx
  client/src/conponent/post/PostList.tsx
  client/src/conponent/postDetail/movie/YoutubePlayer.tsx
  client/src/conponent/postDetail/music/AudioPlayer.tsx
  client/src/conponent/postDetail/music/Player.tsx
  client/src/conponent/postDetail/music/YoutubeList.tsx
  client/src/conponent/postDetail/music/YoutubeListItem.tsx
  client/src/conponent/postDetail/restaurant/Slide.tsx
  client/src/function/request.ts
  client/src/page/AddPost.tsx
  client/src/page/Collect.tsx
  client/src/page/CollectDeatail.tsx
  client/src/page/CollectPost.tsx
  client/src/page/Example.tsx
  client/src/page/Login.tsx
  client/src/page/Main.tsx
  client/src/page/Mypage.tsx
  client/src/page/PostDetail.tsx
  client/src/page/Posts.tsx
  client/src/util/MyApi.ts
  client/src/util/useIntersectorObsevet.ts
  client/src/util/useOuterClick.ts
Labels: enhancement

#77 postapi 코드 정리 & 공용 모달 Context 작업
  client/src/App.tsx
  client/src/conponent/Modal/Modal.tsx
  client/src/conponent/Modal/ModalContextProvider.tsx
  client/src/conponent/Modal/useModal.ts
  client/src/conponent/addPost/MapSearch.tsx
  client/src/conponent/addPost/PlaylistMaker.tsx
  client/src/conponent/mypage/UserEdit.tsx
  client/src/conponent/mypage/UserModal.tsx
  client/src/conponent/parts/Tag.tsx
  client/src/conponent/parts/UserProfile.tsx
  client/src/conponent/post/PostItem.tsx
  client/src/conponent/postDetail/movie/YoutubePlayer.tsx
  client/src/conponent/postDetail/music/AudioPlayer.tsx
  client/src/conponent/postDetail/music/Player.tsx
  client/src/conponent/postDetail/music/YoutubeList.tsx
  client/src/conponent/postDetail/music/YoutubeListItem.tsx
  client/src/function/request.ts
  client/src/function/validFn.ts
  client/src/index.tsx
  client/src/page/AddPost.tsx
  client/src/page/Login.tsx
  client/src/page/PostDetail.tsx
  client/src/page/Posts.tsx
  client/src/page/Signup.tsx
  client/src/util/PostApi.ts
  client/src/util/memberApi.ts
Labels: enhancement

#78 feat: frontend 배포자동화
  .github/workflows/client.yml
Labels: enhancement

#83 design: 게시물페이지 반응형 추가
  client/src/conponent/Header.tsx
  client/src/conponent/collect/CollectItem.tsx
  client/src/conponent/parts/UserProfile.tsx
  client/src/conponent/post/PostItem.tsx
  client/src/conponent/postDetail/music/AudioPlayer.tsx
  client/src/conponent/postDetail/music/YoutubeListItem.tsx
  client/src/page/PostDetail.tsx
  client/src/page/Posts.tsx
  server/src/main/java/com/seb006/server/like/controller/LikeController.java
  server/src/main/java/com/seb006/server/like/service/LikeService.java
  server/src/main/java/com/seb006/server/prfpost/entity/PrfPost.java
  server/src/main/java/com/seb006/server/prfpost/service/PrfPostService.java
  server/src/main/java/com/seb006/server/recruitpost/controller/RecruitPostController.java
  server/src/main/java/com/seb006/server/recruitpost/service/RecruitPostService.java
Labels: enhancement

#84 fix: 배포 후 발견된 오류 수정
  client/src/App.tsx
  client/src/conponent/Header.tsx
  client/src/conponent/Modal/Modal.tsx
  client/src/conponent/Nav.tsx
  client/src/conponent/mypage/UserEdit.tsx
  client/src/conponent/parts/UserProfile.tsx
  client/src/page/Main.tsx
Labels: documentation

#94 design: playlist 수정
  client/src/conponent/Modal/useModal.ts
  client/src/conponent/addPost/MapSearch.tsx
  client/src/conponent/addPost/MoviePreview.tsx
  client/src/conponent/addPost/PlaylistMaker.tsx
  client/src/page/AddPost.tsx
  client/src/page/Login.tsx
  client/src/page/PostDetail.tsx
  client/src/page/Posts.tsx
  client/src/page/Signup.tsx
Labels: enhancement

#96 design: addpost 수정
  client/src/conponent/addPost/MapSearch.tsx
  client/src/conponent/addPost/MoviePreview.tsx
  client/src/conponent/addPost/PlaylistMaker.tsx
  client/src/page/Posts.tsx
Labels: enhancement

#98 design: login signup input title 글씨크기 수정
  client/src/conponent/parts/UserProfile.tsx
  client/src/conponent/post/PostItem.tsx
  client/src/conponent/postDetail/restaurant/Slide.tsx
  client/src/page/Collect.tsx
  client/src/page/Login.tsx
  client/src/page/Signup.tsx
Labels: enhancement

#99 design: favicon 추가
  client/public/favicon.ico
  client/public/index.html
  client/src/page/Mypage.tsx
Labels: documentation

#100 hotfix: 모집글 닫기 추가
  client/src/conponent/collect/CollectItem.tsx
  client/src/conponent/parts/InputNoH.tsx
  client/src/page/Collect.tsx
  client/src/page/CollectDeatail.tsx
  client/src/page/PostDetail.tsx
Labels: enhancement

#110 hotfix: cra기본 사진 삭제
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
Labels: enhancement
